
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox3;
	private global::Gtk.Frame frame3;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.VBox vbox4;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView sourseTextView;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Button convertButton;
	private global::Gtk.Button openFileButton;
	private global::Gtk.Label sourceLabel;
	private global::Gtk.VBox vbox5;
	private global::Gtk.Frame frame4;
	private global::Gtk.Alignment GtkAlignment4;
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	private global::Gtk.NodeView nodeview1;
	private global::Gtk.Label formsLabel;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Button newFormButton;
	private global::Gtk.Button openFormButton;
	private global::Gtk.Button deleteFormButton;
	private global::Gtk.Button button1544;
	private global::Gtk.Frame frame5;
	private global::Gtk.Alignment GtkAlignment7;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TextView resultTextView;
	private global::Gtk.Label xmlLabel;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame ();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.sourseTextView = new global::Gtk.TextView ();
		this.sourseTextView.CanFocus = true;
		this.sourseTextView.Name = "sourseTextView";
		this.GtkScrolledWindow.Add (this.sourseTextView);
		this.vbox4.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow]));
		w2.Position = 0;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.convertButton = new global::Gtk.Button ();
		this.convertButton.CanFocus = true;
		this.convertButton.Name = "convertButton";
		this.convertButton.UseUnderline = true;
		// Container child convertButton.Gtk.Container+ContainerChild
		global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w4 = new global::Gtk.HBox ();
		w4.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w5 = new global::Gtk.Image ();
		w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
		w4.Add (w5);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w7 = new global::Gtk.Label ();
		w7.LabelProp = global::Mono.Unix.Catalog.GetString ("Конвертировать");
		w7.UseUnderline = true;
		w4.Add (w7);
		w3.Add (w4);
		this.convertButton.Add (w3);
		this.hbox1.Add (this.convertButton);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.convertButton]));
		w11.Position = 0;
		w11.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.openFileButton = new global::Gtk.Button ();
		this.openFileButton.CanFocus = true;
		this.openFileButton.Name = "openFileButton";
		this.openFileButton.UseUnderline = true;
		// Container child openFileButton.Gtk.Container+ContainerChild
		global::Gtk.Alignment w12 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w13 = new global::Gtk.HBox ();
		w13.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w14 = new global::Gtk.Image ();
		w14.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-directory", global::Gtk.IconSize.Menu);
		w13.Add (w14);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w16 = new global::Gtk.Label ();
		w16.LabelProp = global::Mono.Unix.Catalog.GetString ("_Открыть файл");
		w16.UseUnderline = true;
		w13.Add (w16);
		w12.Add (w13);
		this.openFileButton.Add (w12);
		this.hbox1.Add (this.openFileButton);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.openFileButton]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		this.vbox4.Add (this.hbox1);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox1]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		this.GtkAlignment.Add (this.vbox4);
		this.frame3.Add (this.GtkAlignment);
		this.sourceLabel = new global::Gtk.Label ();
		this.sourceLabel.Name = "sourceLabel";
		this.sourceLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Исходник</b>");
		this.sourceLabel.UseMarkup = true;
		this.frame3.LabelWidget = this.sourceLabel;
		this.vbox3.Add (this.frame3);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame3]));
		w24.Position = 0;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.frame4 = new global::Gtk.Frame ();
		this.frame4.Name = "frame4";
		this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame4.Gtk.Container+ContainerChild
		this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment4.Name = "GtkAlignment4";
		this.GtkAlignment4.LeftPadding = ((uint)(12));
		// Container child GtkAlignment4.Gtk.Container+ContainerChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.nodeview1 = new global::Gtk.NodeView ();
		this.nodeview1.CanFocus = true;
		this.nodeview1.Name = "nodeview1";
		this.nodeview1.SearchColumn = 0;
		this.GtkScrolledWindow2.Add (this.nodeview1);
		this.GtkAlignment4.Add (this.GtkScrolledWindow2);
		this.frame4.Add (this.GtkAlignment4);
		this.formsLabel = new global::Gtk.Label ();
		this.formsLabel.Name = "formsLabel";
		this.formsLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Формы</b>");
		this.formsLabel.UseMarkup = true;
		this.frame4.LabelWidget = this.formsLabel;
		this.vbox5.Add (this.frame4);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.frame4]));
		w28.Position = 0;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.newFormButton = new global::Gtk.Button ();
		this.newFormButton.CanFocus = true;
		this.newFormButton.Name = "newFormButton";
		this.newFormButton.UseUnderline = true;
		// Container child newFormButton.Gtk.Container+ContainerChild
		global::Gtk.Alignment w29 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w30 = new global::Gtk.HBox ();
		w30.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w31 = new global::Gtk.Image ();
		w31.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-new", global::Gtk.IconSize.Menu);
		w30.Add (w31);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w33 = new global::Gtk.Label ();
		w33.LabelProp = global::Mono.Unix.Catalog.GetString ("Новая форма");
		w33.UseUnderline = true;
		w30.Add (w33);
		w29.Add (w30);
		this.newFormButton.Add (w29);
		this.hbox2.Add (this.newFormButton);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.newFormButton]));
		w37.Position = 0;
		w37.Expand = false;
		w37.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.openFormButton = new global::Gtk.Button ();
		this.openFormButton.CanFocus = true;
		this.openFormButton.Name = "openFormButton";
		this.openFormButton.UseUnderline = true;
		// Container child openFormButton.Gtk.Container+ContainerChild
		global::Gtk.Alignment w38 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w39 = new global::Gtk.HBox ();
		w39.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w40 = new global::Gtk.Image ();
		w40.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
		w39.Add (w40);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w42 = new global::Gtk.Label ();
		w42.LabelProp = global::Mono.Unix.Catalog.GetString ("Редактировать");
		w42.UseUnderline = true;
		w39.Add (w42);
		w38.Add (w39);
		this.openFormButton.Add (w38);
		this.hbox2.Add (this.openFormButton);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.openFormButton]));
		w46.Position = 1;
		w46.Expand = false;
		w46.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.deleteFormButton = new global::Gtk.Button ();
		this.deleteFormButton.CanFocus = true;
		this.deleteFormButton.Name = "deleteFormButton";
		this.deleteFormButton.UseUnderline = true;
		// Container child deleteFormButton.Gtk.Container+ContainerChild
		global::Gtk.Alignment w47 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w48 = new global::Gtk.HBox ();
		w48.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w49 = new global::Gtk.Image ();
		w49.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
		w48.Add (w49);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w51 = new global::Gtk.Label ();
		w51.LabelProp = global::Mono.Unix.Catalog.GetString ("Удалить");
		w51.UseUnderline = true;
		w48.Add (w51);
		w47.Add (w48);
		this.deleteFormButton.Add (w47);
		this.hbox2.Add (this.deleteFormButton);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.deleteFormButton]));
		w55.Position = 2;
		w55.Expand = false;
		w55.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button1544 = new global::Gtk.Button ();
		this.button1544.CanFocus = true;
		this.button1544.Name = "button1544";
		this.button1544.UseUnderline = true;
		// Container child button1544.Gtk.Container+ContainerChild
		global::Gtk.Alignment w56 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w57 = new global::Gtk.HBox ();
		w57.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w58 = new global::Gtk.Image ();
		w58.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-floppy", global::Gtk.IconSize.Menu);
		w57.Add (w58);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w60 = new global::Gtk.Label ();
		w60.LabelProp = global::Mono.Unix.Catalog.GetString ("Сохранить все");
		w60.UseUnderline = true;
		w57.Add (w60);
		w56.Add (w57);
		this.button1544.Add (w56);
		this.hbox2.Add (this.button1544);
		global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button1544]));
		w64.Position = 4;
		w64.Expand = false;
		w64.Fill = false;
		this.vbox5.Add (this.hbox2);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox2]));
		w65.Position = 1;
		w65.Expand = false;
		w65.Fill = false;
		this.vbox3.Add (this.vbox5);
		global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox5]));
		w66.Position = 1;
		// Container child vbox3.Gtk.Box+BoxChild
		this.frame5 = new global::Gtk.Frame ();
		this.frame5.Name = "frame5";
		this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame5.Gtk.Container+ContainerChild
		this.GtkAlignment7 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment7.Name = "GtkAlignment7";
		this.GtkAlignment7.LeftPadding = ((uint)(12));
		// Container child GtkAlignment7.Gtk.Container+ContainerChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.resultTextView = new global::Gtk.TextView ();
		this.resultTextView.CanFocus = true;
		this.resultTextView.Name = "resultTextView";
		this.GtkScrolledWindow1.Add (this.resultTextView);
		this.GtkAlignment7.Add (this.GtkScrolledWindow1);
		this.frame5.Add (this.GtkAlignment7);
		this.xmlLabel = new global::Gtk.Label ();
		this.xmlLabel.Name = "xmlLabel";
		this.xmlLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>XML результат</b>");
		this.xmlLabel.UseMarkup = true;
		this.frame5.LabelWidget = this.xmlLabel;
		this.vbox3.Add (this.frame5);
		global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame5]));
		w70.Position = 2;
		this.Add (this.vbox3);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 784;
		this.DefaultHeight = 644;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.convertButton.Clicked += new global::System.EventHandler (this.OnConvertButtonClicked);
		this.openFileButton.Clicked += new global::System.EventHandler (this.OpenFileButtonClicked);
		this.nodeview1.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnNodeview1ButtonPressEvent);
		this.newFormButton.Clicked += new global::System.EventHandler (this.OnNewFormButtonClicked);
		this.openFormButton.Clicked += new global::System.EventHandler (this.OnOpenFormButtonClicked);
		this.deleteFormButton.Clicked += new global::System.EventHandler (this.OnDeleteFormButtonClicked);
		this.button1544.Clicked += new global::System.EventHandler (this.OnSaveAllButtonClicked);
	}
}
